### ISSUE TITLE
Issue getting SanityCheckRootShell to work 

### ISSUE THREAD

**Issue by AlBurns-MSFT** [Stericson/RootShell#13]
Hi, I'm new to Android development so please forgive my naivety. I have a rooted Nexus 4 running Cyanogenmod. I was able to download RootShell-1.3 and import to Android Studio. I was then able to run on my phone, where I get the output: 

Root found.
[ROOT DENIED EXCEPTION!]
ERROR: No root access to this device

I'm thinking this is because I haven't properly set up RootShell. I believe the issue is because I haven't run RootShell's RootClass. If I simply try to run RootClass I get a few NullPointerExceptions. "You will however need to ensure that jar and dx are in your global environment path." -- not sure how to do this (I'm in Windows), please advise! I also tried to use the command line but I wasn't successful, probably because I entered it wrong. I have RootShell.jar and I placed it in the correct root directory but I haven't been able to craft the command line statement correctly. 

If you could help me troubleshoot this so I can use this library I would greatly appreciate it! I can provide additional information and/or screenshots if needed. 
![screenshot](https://cloud.githubusercontent.com/assets/6195567/13838479/d2c3980e-ebea-11e5-855c-1c739abe84d7.PNG)

**Comment by Lrs121** [comment]
Are you testing on the device? What version of cyanogenmod are you using, eg. Cm12.1, cm13.0, etc.

**Comment by AlBurns-MSFT** [comment]
Yes I am, and 12.1. I'll provide more details a little later today

**Comment by Lrs121** [comment]
Ok, I don't know much about root app development. However, I just wanted to ensure you have root access enabled in the developer options on the device.

**Comment by AlBurns-MSFT** [comment]
Oh, you were right! Thanks! I assumed I had it enabled because I could load a shell and run su and then commands, and the sanitycheck program detected root but failed otherwise. turns out you were correct - i had to enable root in the options.
