### ISSUE TITLE
What license agreement is this available under?

### ISSUE THREAD

**Issue by daj** [Stericson/RootShell#16]
Please could you add some information to your README, or add a LICENSE.txt file to show what license this code is available under?

GitHub have some helpful advice here:
https://help.github.com/articles/licensing-a-repository/

The most permissive and simplest option is probably to add `This project is licensed under the terms of the MIT license.` to your README file.  

There are lots of other options too, e.g. the Square folks typically use an Apache 2 license and add it in a LICENSE.txt file.
https://github.com/square/picasso/blob/master/LICENSE.txt

**Comment by Fusion** [comment]
Dan,

The license text can be found in the wiki: https://github.com/Stericson/RootShell/wiki/Licensing

But you are correct that we could make this more obvious.
