### ISSUE TITLE
seems no implement of `RootShell.getCustomShell`

### ISSUE THREAD

**Issue by yurenchen000** [Stericson/RootShell#24]
https://github.com/Stericson/RootShell/search?utf8=✓&q=getCustomShell&type=

only this Recursive Call:

```java
public static Shell getCustomShell(String shellPath, int timeout) throws IOException, TimeoutException, RootDeniedException
{
    return RootShell.getCustomShell(shellPath, timeout);
}
```

**Comment by consp1racy** [comment]
I'm sure you figured it out by now, but for completeness, it's supposed to be 

    return Shell.startCustomShell(shellPath, timeout);

instead of 

    return RootShell.getCustomShell(shellPath, timeout);

**Comment by yurenchen000** [comment]
> I'm sure you figured it out by now, but for completeness, it's supposed to be
> 
> ```
> return Shell.startCustomShell(shellPath, timeout);
> ```
> instead of
> 
> ```
> return RootShell.getCustomShell(shellPath, timeout);
> ```

??
seems `Shell` also has no method named `startCustomShell` .

**Comment by Stericson** [comment]
https://github.com/Stericson/RootShell/blob/48b5078e9ee2a3600f88663eda27495b2876afb8/src/main/java/com/stericson/RootShell/execution/Shell.java#L908

You might be using and older version?

**Comment by yurenchen000** [comment]
> [RootShell/src/main/java/com/stericson/RootShell/execution/Shell.java](https://github.com/Stericson/RootShell/blob/48b5078e9ee2a3600f88663eda27495b2876afb8/src/main/java/com/stericson/RootShell/execution/Shell.java#L908)
> Line 908 in [48b5078](/Stericson/RootShell/commit/48b5078e9ee2a3600f88663eda27495b2876afb8)
>  public static Shell startCustomShell(String shellPath) throws IOException, TimeoutException, RootDeniedException { 
> You might be using and older version?

oh, you are right, 
sorry, I was mix up `startCustomShell` & `getCustomShell`.

**Comment by consp1racy** [comment]
Well don't close the issue, the error remains the same. RootShell.getCustomShell is not supposed to be recursive.

**Comment by Stericson** [comment]
Ah, I see it. I've fixed it in Master:

https://github.com/Stericson/RootShell/blob/master/src/main/java/com/stericson/RootShell/RootShell.java#L300
